### ISSUE TITLE
Release 4.0.1

### ISSUE THREAD

**Issue by michael-o** [codehaus-plexus/plexus-archiver#111]
@plamentotev @khmarbaise can anyone relase 4.0.1? GH does not accept my SSH public key for some reason. I do require it for MSHARED-787.

**Comment by plamentotev** [comment]
@michael-o I'll release it.

**Comment by plamentotev** [comment]
Done. Released 4.1.0. I've bumped the version because there were new methods.

**Comment by michael-o** [comment]
@plamentotev That's perfect. Thank you very much!
