### ISSUE TITLE
Release 4.2.0

### ISSUE THREAD

**Issue by plamentotev** [codehaus-plexus/plexus-archiver#120]
Hi,

Looks like now we have all things required for reproducible builds(@hboutemy please correct me if I'm wrong) so I think it would be a good to release the changes. If there are no objections I'll have some time next week (Friday 6 September) to make a release.

**Comment by hboutemy** [comment]
nearing success, but not fully yet there: I don't know why ASF Jenkins Linux nodes gets different sha1 than my Linux or Mac box...
https://builds.apache.org/blue/organizations/jenkins/maven-box%2Fmaven-source-plugin/detail/MSOURCES-120/16/pipeline

**Comment by plamentotev** [comment]
@hboutemy for some reason I get 404 for the link you sent. I ran the test on my Linux machine and I got `acf461ff37ddc3c44c620770a73d9cf42f7ca429` as sha1 for the jar file. As the test fails it is obvious that it is not the same as yours but I wonder if it agrees with Jenkins or it is different value. Also if you can share the file from your box so I can compare it with mine maybe I should be able to help with finding the issue (or at least the difference).

**Comment by jeffmaury** [comment]
Would be good to update commons-compress to 1.19
