### ISSUE TITLE
Test ZipArchiverTest.testFixedEntryModificationTime() is TimeZone dependent

### ISSUE THREAD

**Issue by belingueres** [codehaus-plexus/plexus-archiver#122]
My testing environment:

Apache Maven 3.6.2 (40f52333136460af0dc0d7232c0dc0bcf0d9e117; 2019-08-27T12:06:16-03:00)
Maven home: /home/gabriel/.sdkman/candidates/maven/current
Java version: 1.7.0_232, vendor: Azul Systems, Inc., runtime: /home/gabriel/.sdkman/candidates/java/7.0.232-zulu/jre
Default locale: es_AR, platform encoding: UTF-8
OS name: "linux", version: "5.0.0-27-generic", arch: "amd64", family: "unix"

Please note that I'm on a GMT-3 time zone, and the epoch timestamp value returned is 315543600000, which is GMT: Tuesday, 1 January 1980 3:00:00

[org.codehaus.plexus.archiver.zip.ZipArchiverTest.txt](https://github.com/codehaus-plexus/plexus-archiver/files/3593141/org.codehaus.plexus.archiver.zip.ZipArchiverTest.txt)

**Comment by hboutemy** [comment]
fixed by PR #123
