### ISSUE TITLE
Undeclared dependency for Archiver 

### ISSUE THREAD

**Issue by cgp** [codehaus-plexus/plexus-archiver#125]
I'm getting the following error:

`Exception in thread "main" java.lang.NoClassDefFoundError: org/codehaus/plexus/personality/plexus/lifecycle/phase/Contextualizable`

with the following code:

		GZipArchiver archiver = new GZipArchiver();
		archiver.addDirectory(new File("E:\\tmp"));
		archiver.setDestFile(new File("e:\\test.tar.gz"));
		archiver.createArchive();

Looks like Contextualizableis coming over from another project that isn't part of the dependency tree? 

https://codehaus-plexus.github.io/plexus-archiver/apidocs/org/codehaus/plexus/archiver/manager/DefaultArchiverManager.html

**Comment by hboutemy** [comment]
looks like a broken download of plexus-containers: it works perfectly on Travis https://travis-ci.org/codehaus-plexus/plexus-archiver

**Comment by plamentotev** [comment]
Hi, @cgp did @hboutemy suggestion help you or the issue still persist?
