### ISSUE TITLE
reproducible zip entry time depends on local DST

### ISSUE THREAD

**Issue by hboutemy** [codehaus-plexus/plexus-archiver#127]
it is expected to be fully reproducible, but result today, after change of DST, is different from yesterday
calendar used to compute zip timestamp should not be current date but date of the timestamp

**Comment by bmwiedemann** [comment]
Do you need the timezone or could you use such instead?
```java
Calendar cal = Calendar.getInstance(TimeZone.getTimeZone("UTC"));
```
