### ISSUE TITLE
AbstractZipArchiver broken on OpenJDK9 since "project Verona" was integrated

### ISSUE THREAD

**Issue by Sanne** [codehaus-plexus/plexus-archiver#13]
Since the preview build 95 of OpenJDK 9 "project Verona" was integrated in the JDK:
 - http://openjdk.java.net/projects/verona/
 - http://openjdk.java.net/jeps/223

This changed the string formats used by the JVM to report which version is being run, and the `AbstractZipArchiver` currently assumes the old version format.

This seems to affect anyone attempting to build a project using Maven on the latest JDK, as several maven plugins rely on plexus-archiver.

Thanks

**Comment by Sanne** [comment]
See also pr #12

**Comment by krosenvold** [comment]
Thanks!
