### ISSUE TITLE
Missing dependency on org.codehaus.plexus.logging

### ISSUE THREAD

**Issue by JarnoRFB** [codehaus-plexus/plexus-archiver#132]
Hi,
I want to extract a tar.gz file. I installed the archiver in my POM as 

        <dependency>
            <groupId>org.codehaus.plexus</groupId>
            <artifactId>plexus-archiver</artifactId>
            <version>4.2.1</version>
        </dependency>

And I use it in scala like 

```scala
val unarchiver = new TarGZipUnArchiver()
unarchiver.setSourceFile(File(envArchive).toJava)
unarchiver.setDestDirectory(File(tmpDir).toJava)
unarchiver.extract()
```

However, already during compilation I get the error `Class org.codehaus.plexus.logging.AbstractLogEnabled not found - continuing with a stub.`

I am not sure whether there is a dependency missing or some other error, but I am grateful for any help.

**Comment by plamentotev** [comment]
@JarnoRFB is this a Scala code? I guess the compilation error is related to Scala so I'm afraid I can't help you with it. But I do suspect that it has to do with that Plexus Archiver should run inside Plexus Container (you may use Eclipse Sisu with the Plexus extension). If you just want to simply extract tar.gz file and you're not familiar with Plexus you may find it easier to use Apache Commons Compress (the library used by Plexus Archiver to compress/extract). Their site even has example how to extract tar.gz files - https://commons.apache.org/proper/commons-compress/examples.html#Common_Extraction_Logic

**Comment by JarnoRFB** [comment]
Hi, sorry I was not aware that I had to run inside a Plexus container in order to use Plexus Archiver. Thanks for the reply and the pointer to Apache Commons Compress!
