### ISSUE TITLE
plexus-archiver versions 4.2.4, 4.2.5 - unpublished pgp key

### ISSUE THREAD

**Issue by slawekjaranowski** [codehaus-plexus/plexus-archiver#175]
Versions `4.2.4` and `4.2.5` are signed by key with fingerprint `0x4E532BB2FF51BCE63B39A33AA43EC0D4271F7981`
but this key is not published to any known keys servers.

To reproduce pleas run:

```
mvn org.simplify4u.plugins:pgpverify-maven-plugin:show -Dartifact=org.codehaus.plexus:plexus-archiver:4.2.5
```

**Comment by plamentotev** [comment]
Hi,
My bad. Looks like I've somehow messed up my keys. I'll publish my key and I'll be more careful in the future in this regard.

**Comment by slawekjaranowski** [comment]
I confirm key was published to https://keyserver.ubuntu.com/
