### ISSUE TITLE
Looking for the public key which signed version 4.2.2

### ISSUE THREAD

**Issue by rodwiddowson** [codehaus-plexus/plexus-archiver#185]
`org.codehaus.plexus:plexus-archiver:4.2.2:jar` was signed by KeyId `0x44146BCAA1F1E051`.  I have yet to track it down.

I may also have missed the obvious location of your project's KEYS.TXT.

Thanks for any pointers you can provide

Rod

**Comment by plamentotev** [comment]
Hi, this release is signed by me. You can find the public key on  Ubuntu key server - https://keyserver.ubuntu.com/. I'm not aware if Plexus having KEYS file, but if somebody else knows about it, obviously I have to add my keys there.

**Comment by michael-o** [comment]
It should me on MIT's

**Comment by michael-o** [comment]
I don't trust anything open to .com
