### ISSUE TITLE
Archiver 3.0.3 is not on Maven Central

### ISSUE THREAD

**Issue by TobiX** [codehaus-plexus/plexus-archiver#22]
I see a release in this repository, but no artefact in Maven Central. Am I missing something?

**Comment by TobiX** [comment]
Thanks for publishing!

**Comment by krosenvold** [comment]
I'm afraid this is a bit of a botch-up. Whoever published 3.0.3 was probably not aware of the regressions that was delaying the release. 3.0.3 is probably broken.
