### ISSUE TITLE
False negative in isUp2date with empty directory

### ISSUE THREAD

**Issue by tbroyer** [codehaus-plexus/plexus-archiver#24]
The exact problem I'm facing is a combination of maven-compiler-plugin 3.2+ creating a `target/generated-sources/annotations` and adding it as a compile source root, and maven-source-plugin always repackaging the JAR (which causes work to be done in downstream modules even though nothing has actually changed; see details in https://github.com/tbroyer/gwt-maven-archetypes/issues/39)

I tracked down the problem to `AbstractArchiver`'s `isUp2date`: it calls `getLastModified()` on a `PlexusIoFileResourceCollection` which is empty (empty directory) and will therefore return `PlexusIoResource.UNKNOWN_MODIFICATION_DATE`, and when it sees this value it assumes the archive needs to be created again. Ideally, it should, upon seeing that value, check whether the `PlexusIoResourceCollection` is empty or not.

To reproduce, start with this POM:
```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>test</groupId>
  <artifactId>lib</artifactId>
  <version>1.0-SNAPSHOT</version>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.2</version>
        <configuration>
          <source>1.7</source>
          <target>1.7</target>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-source-plugin</artifactId>
        <version>3.0.0</version>
        <executions>
          <execution>
            <goals>
              <goal>jar-no-fork</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
</project>
```

Create a dummy source file, e.g.
```
mkdir -p src/main/java/test
cat src/main/java/test/Test.java <<<EOF
package test;

class Test {
}
EOF
```

then run `mvn package` twice in a row. Second time, maven-source-plugin shouldn't log `Building jar: …`.

If you try with maven-compiler-plugin 3.1, which doesn't add the folder as a source root (see [MCOMPILER-157](https://issues.apache.org/jira/browse/MCOMPILER-157)), this works as expected.

If you modify the code to trigger an annotation processor (such that code is generated into `target/generated-sources/annotations`; you'll want to use maven-compiler-plugin 3.5.1 then, which fixes [MCOMPILER-235](https://issues.apache.org/jira/browse/MCOMPILER-235)), again this works as expected. For example, add the following dependency:
```xml
  <dependencies>
    <dependency>
      <groupId>com.google.auto.value</groupId>
      <artifactId>auto-value</artifactId>
      <version>1.1</version>
    </dependency>
  </dependencies>
```
and modify the `Test.java` file to read:
```java
package test;

import com.google.auto.value.AutoValue;

@AutoValue
abstract class Test {
  public abstract String foo();
}
```

**Comment by plamentotev** [comment]
I think the Plexus Archiver behavior actually is ok.  Well the `target/generated-sources/annotations` is empty now but when the archive was created maybe it was not. Then the archive is outdated and contains obsolete files so it needs to be rebuild.

I've dig some more in the code and I believe the root cause of this defect is the maven-source-plugin and the default inclusion pattern they use so I created issue there - [MSOURCES-95](https://issues.apache.org/jira/browse/MSOURCES-95)

**Comment by tbroyer** [comment]
Ah, good catch, thanks.
