### ISSUE TITLE
Verifing pgp signature for org.codehaus.plexus:plexus-archiver:4.5.0

### ISSUE THREAD

**Issue by slawekjaranowski** [codehaus-plexus/plexus-archiver#244]
Key used to sign `org.codehaus.plexus:plexus-archiver:4.5.0` - `0x09A808E1930F779CC6C54807E4C753D85335E876 `
is only deployed on pgp.mit.edu - which has poor performance and generate many timeouts, 
especially in CI environment where key must be downloaded again on fresh system.

@plamentotev - can you push your key also to https://keyserver.ubuntu.com  ?

**Comment by pzygielo** [comment]
I was under impression that anyone can push public key to PKS.
So I did - and it's there now: https://keyserver.ubuntu.com/pks/lookup?search=0x5335e876&fingerprint=on&op=index

**Comment by slawekjaranowski** [comment]
@pzygielo  thanks, 
I know that everybody can push key to keyserver ... but I prefer such action for key owner.
Owner should know where his key is published.

**Comment by pzygielo** [comment]
Key can be pushed anywhere. Once published - there is (almost) no control over it.

> I prefer such action for key owner.

And the owner decided to use different server than you'd like.

> Owner should know where his key is published.

Is it possible to achieve?

**Comment by plamentotev** [comment]
Hi,

As the ley is published I'll close this issue.
