### ISSUE TITLE
Issues with JDK9

### ISSUE THREAD

**Issue by karussell** [codehaus-plexus/plexus-archiver#30]
I now know that not all in maven is already compatible for JDK9, but maybe you have usage of my error with JDK9 [here](http://stackoverflow.com/q/36583118/194609), here is the full [stacktrace](https://gist.github.com/karussell/aff591db1e46a3d2aafa12f8b4dd2f8d)

**Comment by plamentotev** [comment]
I think this is already fixed with #12

**Comment by karussell** [comment]
Nice, the workaround mentioned by @ctomc made it compiling ... now I can start digging into the failing tests :) !
