### ISSUE TITLE
Change Snappy compressor to io.airlift:aircompressor deploy job failed

### ISSUE THREAD

**Issue by Blackdeathanton** [codehaus-plexus/plexus-archiver#340]
Need the `plexus-archiver` release with `aircompressor` to fix the Snappy compressor CVE. Can you please re-run the deploy job? @slachiewicz 

Thanks!

**Comment by slachiewicz** [comment]
ok, looks like our Deploy job is failing permanently. For now I've disabled it

**Comment by slachiewicz** [comment]
and new version 4.10.0 has been released, please try it

**Comment by Blackdeathanton** [comment]
Thank you very much @slachiewicz !
