### ISSUE TITLE
Get site generation and publishing working.

### ISSUE THREAD

**Issue by khmarbaise** [codehaus-plexus/plexus-archiver#44]
We should use:
- scm-publish:publich-scm

for it.

**Comment by michael-o** [comment]
This did now work for Plexus IO 3.0.0. I have changed parent 5.0 for that.

**Comment by michael-o** [comment]
@khmarbaise I added configuration bits to the POM. I think this should fix the issue.

**Comment by plamentotev** [comment]
Now this seems to be working - the site is generated. @michael-o @khmarbaise can we close this issue or there are still issues unresolved related to the site generation?

**Comment by michael-o** [comment]
Fixed months ago.
