### ISSUE TITLE
Is `generate-test-metadata` execution needed?

### ISSUE THREAD

**Issue by plamentotev** [codehaus-plexus/plexus-archiver#70]
Hi,

I'm working on adding support for modular JAR files. As part of one of my tests I want to create a jar from a Java 9 module. To that end I've compiled some Java classes with Java 9 and placed them inside `src\test\resources`. The issue is that the `generate-test-metadata` goal fails because `plexus-component-metadata:1.7.1`  does not support Java 9 classes. I guess there are couple of solutions here, but I've noticed the following in the `pom.xml`:

```xml
      <plugin>
        <groupId>org.codehaus.plexus</groupId>
        <artifactId>plexus-component-metadata</artifactId>
        <executions>
          <execution>
            <goals>
              <goal>generate-metadata</goal>
            </goals>
          </execution>
        </executions>
      </plugin>
```

Does that means that actually only `generate-metadata` is meant to be executed and `generate-test-metadata` is not needed? `generate-test-metadata` comes from the parent pom. If it's not needed I think it's better to disable it.

**Comment by rfscholte** [comment]
I'm not sure it is worth investigating why the parent calls `generate-test-metadata` by default. Removing it from the parent will do likely more harm. I'd prefer to fix `plexus-component-metadata` instead, in the end it should support Java9 anyway.

**Comment by plamentotev** [comment]
Ok, thanks. Then I'll close it.
