### ISSUE TITLE
Update the test to use JUnit 5

### ISSUE THREAD

**Issue by plamentotev** [codehaus-plexus/plexus-archiver#81]
Now that Java 8 is required we can use JUnit 5. It brings some nice features such as `Assume` that allows a test to be skipped based on run-time conditions. There are some tests that are not run on Windows but currently they are reported as passed, with `Assume` they will be properly reported as skipped.

**Comment by jorsol** [comment]
This should now be changed to JUnit 5 😉

**Comment by plamentotev** [comment]
I've updated the description. @jorsol do you work on that or you just noticed the ticket. I ask because I've just started playing around with migrating to JUnit5.

**Comment by jorsol** [comment]
> I've updated the description. @jorsol do you work on that or you just noticed the ticket. I ask because I've just started playing around with migrating to JUnit5.

I just noticed the ticket, I wish to work on this but I don't have enough time to tackle this.

**Comment by plamentotev** [comment]
I've migrated the test and they work with JUnit 5. I think I'll do some obvious improvements that are supported in JUnit 5 and then merge it master. Any suggestion/comments are greatly appreciated.
