### ISSUE TITLE
There are broken links pointing to Codehaus

### ISSUE THREAD

**Issue by plamentotev** [codehaus-plexus/plexus-archiver#82]
In Plexus Archiver and Plexus IO there are still links that point to Codehaus and thus they are broken.

**Comment by plamentotev** [comment]
Actually this is not really a bug. I'll add new 'Documentation' label. Any objections?

**Comment by khmarbaise** [comment]
No it's much better. And yes it's not really a `bug`....

**Comment by plamentotev** [comment]
This is not completed as for example https://codehaus-plexus.github.io/plexus-archiver/mailing-lists.html this has broken links.

**Comment by slawekjaranowski** [comment]
There is a problem with parent ... this should help https://github.com/codehaus-plexus/plexus-pom/pull/161
With new version of parent I can fix it 😄

**Comment by slawekjaranowski** [comment]
For the latest site should be ok - I can not find broken links.
One broken link is for https://codehaus-plexus.github.io/plexus-components/ but it is a problem in plexus-components site

So I close it.
